### PR TITLE
add history variable selection and plotting

### PR DESCRIPTION
**Pull request by evalieungh**

### CODE REVIEW

**Comment by evalieungh** [comment]
Hi! These additions are not really complete, but now you can see what I've been working on. 
The list of history/output variables is still quite long and should be shortened. Feel free to suggest variables to cut away, or if any important ones are missing.

**Review by emiliano-gelati — COMMENTED** [review]
@evalieungh: is this still work in progress or do you want it reviewed?

**Comment by evalieungh** [comment]
Work in progress, I think. There shouldn't be any conflicts, but this is less important stuff that is not a priority! Made the pull request mostly so you could see which variables I have picked out and we can reduce the list together.

**Comment by evalieungh** [comment]
Are these changes obsolete with your recent developments, @lasseke ?

**Comment by lasseke** [comment]
> Are these changes obsolete with your recent developments, @lasseke ?

@evalieungh I wouldn't say obsolete, your python script draft and [this notebook](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/notebooks/plot_example.ipynb) do similar things as of now, but one (yours) could be used to automate creating and saving plot output for multiple variables at once, and the other one (notebook) for quick interactive exploration. They could eventually also be combined, i.e., your script could be executed from within the notebook to automatically create and save certain output plots. The problem is that it wouldn't run in its current stage, so we should not merge this yet :)

Plus, the variable subset in the json file is a good starting point for potentially adaptable fates parameters! Just be aware that it's not proper json format in its current form, you cannot have any comments/docstrings (see text between """ at the top of the file) or variable assignments (-> remove 'output_variables_subset =') in there. I'd say let's keep this as a draft for now!

**Pull request closed without merging**
