### PR TITLE
Updata ctsm version to ctsm5.1.dev090

### PR DESCRIPTION
**Pull request by huitang-earth**
Major changes:

- installation scripts for container in ".machine/NREC_VM_setup/privileged/".
- configuration files for different components of NorESM in "config/".

The updates have been tested for ALP1 site in the container. Others sites still need to be be implemented to work with the new ctsm version. 

The pull request addresses issue #89

### CODE REVIEW

**Comment by evalieungh** [comment]
It will be great to work with the newer versions. I have no idea how/if these changes work with the new GUI, but it seems sensible to start a new branch with this and develop further there. 
To add more SeedClim sites, do we need to change other files than  [config/cime/modelgrid_aliases_nuopc.xml](https://github.com/NorESMhub/NorESM_LandSites_Platform/pull/100/files#diff-a918ae9da3dd2d734d63253d96eac4ab62efcd21292ad95c6263e04c4afa8ec4) and config/cime/stream_definition_datm.xml?

**Review by evalieungh — APPROVED** [review]

**Comment by ka7eh** [comment]
@huitang-earth I moved your changes to the new repos and they work fine, but I'm not getting any output for ALP1.
Do I need new input files for this to work? Are there any specific configs I should use to create a test case?

**Comment by huitang-earth** [comment]
@ka7eh, I indeed have proper output from my test run. So, there might be some problems with your setting. 

Q1: Yes, you need to input data to make it work. I used the [old inputdata](https://uio-my.sharepoint.com/:u:/r/personal/huit_uio_no/Documents/inputdata_version2.0.0_ALP1.tar?csf=1&web=1&e=VJkdZa) for the platform and update it to work properly with the [new model version](https://uio-my.sharepoint.com/:u:/r/personal/huit_uio_no/Documents/inputdata_ALP1_ctsm5.1dev090.tar?csf=1&web=1&e=6ch6q6). You can download both versions from the links provided above. 


Q2: I use the following command to create my test case. It should also work for you. Note that I do not use Lasse's python scripts to create the case. Instead, I prefer to use command line for testing runs. This will be easier to debug for me. :)
 
./create_newcase --case ../../../data/cases/ALP1_test3 --compset 2000_DATM%1PTGSWP3_CLM50%FATES_SICE_SOCN_MOSART_SGLC_SWAV --res 1x1_ALP1 --machine container-nlp --run-unsupported

**Comment by huitang-earth** [comment]
@ka7eh , I delete "clmfates_interfaceMod.F90" as a bug fix for older CTSM version, this is not needed to do such bug fix any more as it is already fixed in the main branch of CTSM. 

I am using NorESM branch (https://github.com/NorESMhub/NorESM/tree/noresm_landsites) as it is now.

My case directory (including "run" and "bld" directory) is [here](https://uio-my.sharepoint.com/:u:/g/personal/huit_uio_no/Edx9VvG_NEVHiDgZ38tC3ukBT5dNbiI0ZUHNWq5hxYaWZQ?e=CJGphH). You can "diff" the setting with your case to see if there are any changes that should be made.

Let me know if you still have problems. There might be some changes I've made are not included in the PR.

**Comment by ka7eh** [comment]
@huitang-earth I noticed you haven't set `fates_paramfile` and `fsurdat` in `user_nl_clm`. I removed those and now I can get results with your latest changes.

So now the question is if those two params are needed in the namelist file.
Before, their values were set like this for ALP1:

```
fates_paramfile = '<data_path>/inputdata/lnd/clm2/paramdata/fates_params_api.14.0.0_12pft_c200921.nc'
fsurdat = '<data_path>/inputdata/lnd/clm2/surfdata_map/ALP1/surfdata_ALP1_simyr2000.nc'
```

**Comment by huitang-earth** [comment]
@ka7eh It is great that you are able to run through the case. 

Ideally, "fates_paramfile" and "fsurdat" will be set in **namelist_defaults_ctsm.xml**. See line:
https://github.com/huitang-earth/NorESM_LandSites_Platform/blob/cdb869e51632652e81caf6af40a4ab82a523e42d/config/ctsm/namelist_defaults_ctsm.xml#L494

https://github.com/huitang-earth/NorESM_LandSites_Platform/blob/cdb869e51632652e81caf6af40a4ab82a523e42d/config/ctsm/namelist_defaults_ctsm.xml#L1032

So, you don't need the write anything in `user_nl_clm` for **the default setting and default sites**. Only if the users want to use different parameter and surface data files for their customized simulations, they can do so.

**Pull request closed without merging**
